# Generated by Django 4.2.7 on 2023-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateField(),
        ),
    ]
